openapi: 3.0.3
info:
  title: github-explorer API
  version: 1.0.0-SNAPSHOT
paths:
  /repositories:
    get:
      tags:
        - Repository Resource
      parameters:
        - name: userName
          in: query
          description: The user name for which repositories are to be retrieved
          required: true
          schema:
            type: string
          example: john_doe
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          content:
            application/json:
              example:
                message: "Required parameter missed: userName"
                status: 400
        "406":
          description: Not Acceptable
          content:
            application/json:
              example:
                message: "Media type application/xml is not supported by this API."
                status: 406
        "404":
          description: Not Found
          content:
            application/json:
              example:
                message: "GithubAPI responded with status 404. Original Message: Not Found."
                status: 404
