
openapi: 3.0.3
info:
  title: github-explorer API
  version: 1.0.0-SNAPSHOT
paths:
  /repositories:
    get:
      tags:
      - Repository Resource
      parameters:
      - name: userName
        in: query
        description: The user name for which repositories are to be retrieved
        required: true
        schema:
          type: string
        example: john_doe
      responses:
        "200":
          description: OK
