openapi: 3.0.3
info:
  title: github-explorer API
  version: 1.0.0-SNAPSHOT
paths:
  /repositories:
    get:
      tags:
        - Repository Resource
      parameters:
        - name: userName
          in: query
          description: The user name for which repositories are to be retrieved
          required: true
          schema:
            type: string
          example: john_doe
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                - $ref: '#/components/schemas/GitHubRepository'
        "400":
          description: Bad Request
          content:
            application/json:
              example:
                message: "Required parameter missed: userName"
                status: 400
        "406":
          description: Not Acceptable
          content:
            application/json:
              example:
                message: "Media type application/xml is not supported by this API."
                status: 406
        "404":
          description: Not Found
          content:
            application/json:
              example:
                message: "GithubAPI responded with status 404. Original Message: Not Found."
                status: 404


components:
  schemas:
    GitHubRepository:
      type: object
      properties:
        id:
          type: integer
          example: 741911868
        name:
          type: string
          example: github-explorer
        owner:
          $ref: '#/components/schemas/GitHubUser'
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
        fork:
          type: boolean
          example: false

    GitHubUser:
      type: object
      properties:
        login:
          type: string
          example: Alex-Bezruk
        id:
          type: integer
          example: 30620490
        url:
          type: string
          format: uri
          example: https://api.github.com/users/Alex-Bezruk

    Branch:
      type: object
      properties:
        name:
          type: string
          example: master
        commit:
          $ref: '#/components/schemas/Commit'

    Commit:
      type: object
      properties:
        sha:
          type: string
          example: 5a5be8a021a14e6f51ca879d9e935c296156c826
